name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Frontend Dependencies
      run: cd frontend && npm ci

    - name: Run Frontend Tests
      run: cd frontend && npm test

    - name: Build Frontend
      run: cd frontend && npm run build

#  build-backend:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Use Node.js
#      uses: actions/setup-node@v2
#      with:
#        node-version: '14.x'
#
#    - name: Install Backend Dependencies
#      run: cd express_graphql && npm ci
#
#    - name: Run Backend Tests
#      run: cd express_graphql && npm test
      