name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install frontend dependencies
      run: cd frontend && npm install

    - name: Build frontend
      run: cd frontend && npm run build

    - name: Test frontend
      run: cd frontend && npm test
      env:
        REACT_APP_CLERK_PUBLISHABLE_KEY: ${{ secrets.REACT_APP_CLERK_PUBLISHABLE_KEY }}
    
    - name: Install backend dependencies
      run: cd backend && npm install
    
    - name: Test backend
      run: cd backend && npm test

    - name: Test start backend server
      run: |
        cd backend
        npm install
        timeout 1m npm run start || true
